# Generated by Django 4.0.10 on 2023-12-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
