# Generated by Django 4.0.10 on 2023-12-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='feedback_en',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_uk',
            field=models.CharField(default='', max_length=500),
        ),
    ]
