# Generated by Django 4.0.10 on 2023-12-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advantage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventage',
            name='img',
            field=models.ImageField(blank='true', upload_to='adventage'),
        ),
    ]
