# Generated by Django 4.0.10 on 2023-12-17 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advantage', '0002_alter_adventage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventage',
            name='img',
            field=models.FileField(blank='true', upload_to='adventage/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpeg', 'jpg'])]),
        ),
    ]
